# Configuration for Variational Autoencoder experiment
# Experiment: vae_anomaly_detection

# Data configuration
data:
  dataset_path: "../NSL-KDD_Dataset"
  train_file: "KDDTrain+.txt"
  test_file: "KDDTest+.txt"
  validation_split: 0.2
  batch_size: 256
  num_workers: 4
  shuffle_train: true

# Model configuration
model:
  type: "vae"
  input_dim: 41
  hidden_dims: [32, 16]
  latent_dim: 6
  activation: "relu"
  use_batch_norm: true
  dropout_rate: 0.1

# VAE-specific configuration
vae:
  beta: 1.0  # Weight for KL divergence term

# Training configuration
training:
  num_epochs: 120
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "reduce_plateau"
  loss_type: "vae"  # Special loss for VAE
  
  early_stopping_patience: 15
  min_delta: 1e-6
  
  gradient_clip_value: 1.0
  weight_decay: 1e-5
  
  log_interval: 100
  save_interval: 10

# GPU configuration
device:
  use_cuda: true
  cuda_device: 0
  memory_efficient: true

# Evaluation configuration
evaluation:
  threshold_methods:
    - "percentile_95"
    - "percentile_98"
    - "percentile_99"
    - "optimal_f1"
  error_type: "mse"
  save_plots: true
  plot_format: "png"

# Experiment tracking
experiment:
  name: "vae_autoencoder"
  description: "Variational autoencoder for anomaly detection"
  save_model: true
  save_results: true
  save_plots: true
  results_dir: "../results"
  models_dir: "../models"
  plots_dir: "../plots"

seed: 42